### ISSUE TITLE
--init_method connected not present

### ISSUE THREAD

**Issue by rschenck** [aroth85/pyclone#10]
The `--init_method connected` does not appear to be present in v0.13.1. Is that accurate? I receive an error for some other tools based on the lack of this in PyClone.

**Comment by bend87** [comment]
If you are running PyClone on Mac and you installed it using Anaconda, you may only have version 0.13.0 (the latest OS X release available there), which does not have this option. You'll have to build PyClone from source, i.e., clone the repo and install manually.

**Comment by rschenck** [comment]
Indeed. It is only v0.13.0! Cheers
